FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN go build -o service-a ./cmd/server

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/service-a .

EXPOSE 8080

CMD ["./service-a"]